name: Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Enable manual triggering

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for better emulator support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Verify Maven installation
      run: mvn -version

    - name: Install Appium
      run: npm install -g appium

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install Android emulator
      run: |
        sdkmanager "system-images;android-30;google_apis;x86_64"
        sdkmanager "emulator"
        sdkmanager "platform-tools"

    - name: Create Android emulator
      run: |
        avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64" -d "pixel_xl" --force

    - name: Start Android emulator
      run: |
        emulator -avd test_emulator -no-audio -no-window -no-snapshot -no-boot-anim &
        adb wait-for-device
        adb shell input keyevent 82

    - name: Start Appium server
      run: appium &
      env:
        APPIUM_PORT: 4723

    - name: Run Maven tests
      run: mvn test
      env:
        APPIUM_URL: http://localhost:4723/wd/hub
