name: Appium Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Android SDK and Maven)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      # Start Docker Android emulator with Appium
      - name: Start Docker Android Emulator
        run: |
          docker pull budtmo/docker-android:emulator_11.0
          docker run -d \
            --name android-emulator \
            -p 4723:4723 \  # Appium port
            -p 5554:5554 \  # Emulator port
            -e DEVICE="Pixel 5" \  # Emulator device name
            -e APPIUM=true \  # Enable Appium
            --privileged \  # Required for Android emulator
            budtmo/docker-android:emulator_11.0

      # Wait for the emulator to boot
      - name: Wait for Emulator to Boot
        run: |
          docker exec android-emulator wait-for-emulator
          docker exec android-emulator adb devices

      # Install Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: "3.8.6"

      # Run Appium tests using Maven
      - name: Run Appium Tests
        run: |
          mvn clean test

      # Stop and remove the Docker container
      - name: Clean up Docker container
        if: always()
        run: |
          docker stop android-emulator
          docker rm android-emulator
